[project]
name = "postech-ml-challenge-fase-2"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10, <3.14"
dependencies = [
    "torch>=2.2.0",
    "scikit-learn>=1.4.0",
    "mlflow>=2.10.0",
    "dvc>=3.40.0",
    "pydantic-settings>=2.2.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]


[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.3.0",
    "pre-commit>=3.6.0",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",   # erros de pycodestyle
    "W",   # avisos de pycodestyle
    "F",   # pyflakes
    "I",   # isort (ordenação de importações)
    "N",   # pep8-naming (padrão de nomenclatura)
    "D",   # pydocstyle (docstrings)
    "UP",  # pyupgrade
]
ignore = [
    "D100", # Falta de docstring em módulo público
    "D104", # Falta de docstring em pacote público
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.pyright]
extraPaths = ["."]
venvPath = "."
venv = ".venv"
